# Generated by Django 5.2.4 on 2025-08-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250802_1107'),
    ]

    operations = [
    ]
